import 'dart:convert';
import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

import '../core/utils/currency.dart';

const _languageKey = 'settings_language';
const _currencyCodeKey = 'settings_currency_code';
const _currencyRateKeyPrefix = 'settings_currency_rate_';
const _emailNotificationsKey = 'settings_email_notifications';
const _phoneNotificationsKey = 'settings_phone_notifications';

const kSupportedAppLanguages = [
  'English',
  'French',
  'Spanish',
  'Arabic',
  'Twi',
];

final appSettingsControllerProvider =
    StateNotifierProvider<AppSettingsController, AppSettings>((ref) {
  return AppSettingsController(AppSettingsController._initialSettings);
});

class AppSettings {
  const AppSettings({
    this.language = 'English',
    this.currencyCode = 'GHS',
    this.emailNotifications = true,
    this.phoneNotifications = true,
  });

  final String language;
  final String currencyCode;
  final bool emailNotifications;
  final bool phoneNotifications;

  String t(String text) {
    if (language == 'English') return text;
    return _translations[language]?[text] ?? text;
  }

  AppSettings copyWith({
    String? language,
    String? currencyCode,
    bool? emailNotifications,
    bool? phoneNotifications,
  }) {
    return AppSettings(
      language: language ?? this.language,
      currencyCode: currencyCode ?? this.currencyCode,
      emailNotifications: emailNotifications ?? this.emailNotifications,
      phoneNotifications: phoneNotifications ?? this.phoneNotifications,
    );
  }
}

const _translations = <String, Map<String, String>>{
  'French': {
    'ProSME   Find Professionals': 'ProSME   Trouver des professionnels',
    'ProSME': 'ProSME',
    'Home': 'Accueil',
    'Upload': 'Publier',
    'Chat': 'Discussion',
    'Chats': 'Discussions',
    'Bookings': 'Réservations',
    'Profile': 'Profil',
    'Artisan Dashboard': 'Tableau artisan',
    'Artisan': 'Artisan',
    'Listings': 'Annonces',
    'Jobs': 'Travaux',
    'Settings': 'Paramètres',
    'Search requests': 'Rechercher des demandes',
    'Sign in to view chats': 'Connectez-vous pour voir les discussions',
    'No chats yet. Open a professional listing and tap Chat to start.':
        'Aucune discussion. Ouvrez une annonce et appuyez sur Discussion.',
    'No messages yet': 'Aucun message',
    'Delete chat': 'Supprimer la discussion',
    'Delete this conversation from your chat home?':
        'Supprimer cette conversation de vos discussions ?',
    'Cancel': 'Annuler',
    'Delete': 'Supprimer',
    'Search results': 'Resultats de recherche',
    'Open service requests': 'Demandes ouvertes',
    'Matching requests': 'Demandes correspondantes',
    'All professionals': 'Tous les professionnels',
    'Matching professionals': 'Professionnels correspondants',
    'Latest Artisan Updates': 'Dernieres mises a jour',
    'No artisan updates yet.': 'Aucune mise a jour pour le moment.',
    'Featured Professionals': 'Professionnels en vedette',
    'View All': 'Tout voir',
    'No professionals found for this search.':
        'Aucun professionnel trouve pour cette recherche.',
    'Popular Services': 'Services populaires',
    'Open Service Requests': 'Demandes de service ouvertes',
    'Post': 'Publier',
    'pros': 'pros',
    'Verified': 'Verifie',
    'active service': 'service actif',
    'active services': 'services actifs',
    'won bids': 'offres gagnees',
    'Unavailable': 'Indisponible',
    'Available': 'Disponible',
    'From': 'A partir de',
    'comment': 'commentaire',
    'comments': 'commentaires',
    'View profile & comments': 'Voir le profil et les commentaires',
    'Busy': 'Occupe',
    'Book Now': 'Reserver',
    'Listing': 'Annonce',
    'Professional': 'Professionnel',
    'Professional profile': 'Profil professionnel',
    'Unavailable now': 'Indisponible maintenant',
    'Artisan unavailable': 'Artisan indisponible',
    'Bookmark': 'Favori',
    'Bookmarked': 'Ajoute aux favoris',
    'This listing is no longer available.':
        'Cette annonce n est plus disponible.',
    'Could not load this listing. Check your connection and try again.':
        'Impossible de charger cette annonce. Verifiez votre connexion.',
    'Loading listing...': 'Chargement de l annonce...',
    'This artisan is currently unavailable.':
        'Cet artisan est actuellement indisponible.',
    'You cannot chat with yourself.':
        'Vous ne pouvez pas discuter avec vous-meme.',
    'Could not start chat. Please try again.':
        'Impossible de demarrer la discussion. Reessayez.',
    'Could not load professional profile.':
        'Impossible de charger le profil professionnel.',
    'Loading profile...': 'Chargement du profil...',
    'Services': 'Services',
    'No active services': 'Aucun service actif',
    'Comments': 'Commentaires',
    'No comments yet': 'Aucun commentaire pour le moment',
    'Active services': 'Services actifs',
    'Bids won': 'Offres gagnees',
    'Completed reviews': 'Avis termines',
    'Upload service request': 'Publier une demande de service',
    'Service title': 'Titre du service',
    'Describe your need': 'Decrivez votre besoin',
    'Location': 'Localisation',
    'Title is required': 'Le titre est requis',
    'Description is required': 'La description est requise',
    'Location is required': 'La localisation est requise',
    'Enter a valid budget': 'Entrez un budget valide',
    'Budget': 'Budget',
    'Uploading...': 'Publication...',
    'My uploaded requests': 'Mes demandes publiees',
    'No uploads yet.': 'Aucune publication pour le moment.',
    'Enter a known address or use your phone location.':
        'Entrez une adresse connue ou utilisez la localisation du telephone.',
    'Use current location': 'Utiliser la localisation actuelle',
    'Location added to request.': 'Localisation ajoutee a la demande.',
    'Could not get location': 'Impossible d obtenir la localisation',
    'Location permission is required.':
        'L autorisation de localisation est requise.',
    'Sign in to upload requests': 'Connectez-vous pour publier des demandes',
    'Request uploaded successfully.': 'Demande publiee avec succes.',
    'Could not upload request. Check Supabase setup.':
        'Impossible de publier la demande. Verifiez Supabase.',
    'Could not load uploads. Check Supabase credentials and try again.':
        'Impossible de charger les publications. Verifiez Supabase.',
    'Notifications': 'Notifications',
    'Refresh': 'Actualiser',
    'Could not load notifications.': 'Impossible de charger les notifications.',
    'Loading notifications...': 'Chargement des notifications...',
    'All': 'Tout',
    'Unread': 'Non lues',
    'Read': 'Lues',
    'Type': 'Type',
    'Date': 'Date',
    'Clear date filter': 'Effacer le filtre de date',
    'No notifications': 'Aucune notification',
    'Mark read': 'Marquer comme lue',
    'Notification deleted.': 'Notification supprimee.',
    'Wallet': 'Portefeuille',
    'Track accepted bids and money flow.':
        'Suivez les offres acceptees et les flux d argent.',
    'Work history': 'Historique des travaux',
    'Accepted and rejected bids and requests.':
        'Offres acceptees ou refusees et demandes.',
    'Bid history': 'Historique des offres',
    'Request history': 'Historique des demandes',
    'Loading history...': 'Chargement de l historique...',
    'No bid history yet.': 'Aucun historique d offres.',
    'No request history yet.': 'Aucun historique de demandes.',
    'Could not load work history.':
        'Impossible de charger l historique des travaux.',
    'Wallet transactions': 'Transactions du portefeuille',
    'Wallet tracking': 'Suivi du portefeuille',
    'Reports and invoices': 'Rapports et factures',
    'Tracked amount': 'Montant suivi',
    'Completed work': 'Travaux termines',
    'Customers': 'Clients',
    'Artisans': 'Artisans',
    'accepted': 'accepte',
    'rejected': 'refuse',
    'completed': 'termine',
    'open': 'ouvert',
    'Accepted and completed bid money flow':
        'Flux des offres acceptees et terminees',
    'Tracked accepted bids': 'Offres acceptees suivies',
    'Money flow from accepted work.': 'Flux d argent des travaux acceptes.',
    'No wallet activity yet': 'Aucune activite de portefeuille',
    'Could not load wallet.': 'Impossible de charger le portefeuille.',
    'Loading wallet...': 'Chargement du portefeuille...',
    'bid accepted': 'offre acceptee',
    'Wallet flow': 'Flux du portefeuille',
    'Latest accepted bid money flow.':
        'Dernier flux d argent des offres acceptees.',
    'Hello': 'Bonjour',
    'Favourites': 'Favoris',
    'Mark services unavailable': 'Marquer les services indisponibles',
    'Chat and booking buttons show unavailable to users.':
        'Les boutons de discussion et de reservation indiquent indisponible.',
    'Users can chat and book your active services.':
        'Les utilisateurs peuvent discuter et reserver vos services actifs.',
    'Services marked unavailable.': 'Services marques indisponibles.',
    'Services marked available.': 'Services marques disponibles.',
    'Could not update status': 'Impossible de mettre a jour le statut',
    'Verified artisan': 'Artisan verifie',
    'Verification needed': 'Verification requise',
    'Customers can see your verified badge.':
        'Les clients peuvent voir votre badge verifie.',
    'Upload ID documents so Support can verify your profile.':
        'Televersez vos pieces pour que le support verifie votre profil.',
    'Manage your services': 'Gerez vos services',
    'My listings': 'Mes annonces',
    'Requests': 'Demandes',
    'Negotiations': 'Negociations',
    'New Job Requests': 'Nouvelles demandes',
    'Could not load requests': 'Impossible de charger les demandes',
    'No customer requests yet': 'Aucune demande client pour le moment',
    'New jobs will appear here when users post them.':
        'Les nouveaux travaux apparaitront ici quand les clients les publient.',
    'Bid': 'Offrir',
    'Won': 'Gagne',
    'Bid sent. Chat opens after the customer accepts it.':
        'Offre envoyee. La discussion s ouvre apres acceptation du client.',
    'Bid updated. Chat opens after the customer accepts it.':
        'Offre mise a jour. La discussion s ouvre apres acceptation du client.',
    'Chat after accept': 'Discussion apres acceptation',
    'Verified account': 'Compte verifie',
    'Verification': 'Verification',
    'Your profile shows a public verified checkmark.':
        'Votre profil affiche un badge verifie public.',
    'Submit or update your ID for Support review.':
        'Envoyez ou mettez a jour votre piece d identite pour verification.',
    'Account settings': 'Parametres du compte',
    'Username, phone, email, password, and privacy.':
        'Nom d utilisateur, telephone, e-mail, mot de passe et confidentialite.',
    'Open': 'Ouvrir',
    'App settings': 'Parametres de l application',
    'Language, dark mode, and notifications.':
        'Langue, mode sombre et notifications.',
    'History, bid, chat, and account alerts.':
        'Historique, offres, discussions et alertes de compte.',
    'Logout': 'Deconnexion',
    'Delete account': 'Supprimer le compte',
    'Sign in to continue': 'Connectez-vous pour continuer',
    'Manage your profile and settings.':
        'Gerez votre profil et vos parametres.',
    'Dark mode': 'Mode sombre',
    'Email notifications': 'Notifications par e-mail',
    'Phone notifications': 'Notifications telephone',
    'Language': 'Langue',
    'Currency': 'Devise',
    'Close': 'Fermer',
    'Username': 'Nom d utilisateur',
    'Edit': 'Modifier',
    'Add full name': 'Ajouter le nom complet',
    'Full name or business contact name':
        'Nom complet ou contact professionnel',
    'Full name': 'Nom complet',
    'Add phone': 'Ajouter un telephone',
    'Phone number and country code': 'Telephone et indicatif du pays',
    'Country code': 'Indicatif du pays',
    'Add profile description': 'Ajouter une description du profil',
    'Company or artisan profile description':
        'Description de l entreprise ou de l artisan',
    'Customer profile description': 'Description du profil client',
    'Account security': 'Securite du compte',
    'Email codes, password recovery, and Google verification are handled by Supabase.':
        'Les codes e-mail, la recuperation du mot de passe et Google sont geres par Supabase.',
    'Privacy': 'Confidentialite',
    'Support': 'Assistance',
    'Terms of Service': 'Conditions d utilisation',
    'About': 'A propos',
    'About Pro SME': 'A propos de Pro SME',
    'Pro SME helps customers connect with verified SMEs and artisans.':
        'Pro SME aide les clients a trouver des PME et artisans verifies.',
    'Artisan profile': 'Profil artisan',
    'Customer profile': 'Profil client',
    'saved listing': 'annonce enregistree',
    'saved listings': 'annonces enregistrees',
    'No favourites added': 'Aucun favori ajoute',
    'Tap to view your saved listings.':
        'Appuyez pour voir vos annonces enregistrees.',
    'Save all your favourites in one place using the bookmark icon.':
        'Enregistrez vos favoris au meme endroit avec l icone favori.',
    'Job details': 'Details du travail',
    'Could not load this job': 'Impossible de charger ce travail',
    'This job is no longer available.': 'Ce travail n est plus disponible.',
    'Before you continue': 'Avant de continuer',
    'Negotiate in chat and confirm verification status before payment or site visits.':
        'Negociez dans la discussion et confirmez la verification avant paiement ou visite.',
    'Sign in to bid or chat': 'Connectez-vous pour offrir ou discuter',
    'Only artisans can bid on service requests.':
        'Seuls les artisans peuvent faire une offre.',
    'budget': 'budget',
    'Edit job': 'Modifier le travail',
    'Update details or add an image URL.':
        'Modifiez les details ou ajoutez une URL d image.',
    'Delete job': 'Supprimer le travail',
    'Permanently remove this request.':
        'Supprimer definitivement cette demande.',
    'Delete job request': 'Supprimer la demande',
    'Remove job request': 'Retirer la demande',
    'Remove': 'Retirer',
    'permanently?': 'definitivement ?',
    'from your list?': 'de votre liste ?',
    'Job request deleted.': 'Demande supprimee.',
    'Request removed from your list.': 'Demande retiree de votre liste.',
    'Could not delete job request': 'Impossible de supprimer la demande',
    'Title': 'Titre',
    'Description': 'Description',
    'Required': 'Requis',
    'Image URL (optional)': 'URL image (facultatif)',
    'Save': 'Enregistrer',
    'Job updated.': 'Travail mis a jour.',
    'Could not update job': 'Impossible de mettre a jour le travail',
    'Send a bid': 'Envoyer une offre',
    'Edit your bid': 'Modifier votre offre',
    'This bid has been accepted and can no longer be changed.':
        'Cette offre a ete acceptee et ne peut plus etre modifiee.',
    'You already bid on this job. Update your amount or message here.':
        'Vous avez deja fait une offre. Modifiez le montant ou le message ici.',
    'Your price': 'Votre prix',
    'Enter a valid price': 'Entrez un prix valide',
    'Message': 'Message',
    'Explain your offer, availability, or questions.':
        'Expliquez votre offre, disponibilite ou questions.',
    'Message is required': 'Le message est requis',
    'Send bid and open chat': 'Envoyer l offre',
    'Update bid and open chat': 'Mettre a jour l offre',
    'Could not send bid': 'Impossible d envoyer l offre',
    'Could not load bids': 'Impossible de charger les offres',
    'No bids yet. Artisans will appear here after they respond.':
        'Aucune offre. Les artisans apparaitront apres leur reponse.',
    'won bid': 'offre gagnee',
    'Rated': 'Note',
    'Accept': 'Accepter',
    'Rate artisan': 'Noter l artisan',
    'Update rating': 'Modifier la note',
    'Could not open chat': 'Impossible d ouvrir la discussion',
    'Bid accepted for': 'Offre acceptee pour',
    'Could not accept bid': 'Impossible d accepter l offre',
    'Comment': 'Commentaire',
    'Describe the completed job.': 'Decrivez le travail termine.',
    'Save rating': 'Enregistrer la note',
    'Rating saved.': 'Note enregistree.',
    'Could not save rating': 'Impossible d enregistrer la note',
    'Work location': 'Lieu du travail',
    'Directions': 'Itineraire',
    'Please sign in to view jobs.': 'Connectez-vous pour voir les travaux.',
    'Create job': 'Creer un travail',
    'Could not load jobs': 'Impossible de charger les travaux',
    'No bookings yet. Create your first request.':
        'Aucune reservation. Creez votre premiere demande.',
    'Edit bid': 'Modifier l offre',
    'View bids': 'Voir les offres',
    'View': 'Voir',
    'Create': 'Creer',
    'Search job requests': 'Rechercher des demandes',
    'Newest first': 'Plus recent d abord',
    'Oldest first': 'Plus ancien d abord',
    'Country': 'Pays',
    'Region': 'Region',
    'Any country': 'Tout pays',
    'Any region': 'Toute region',
    'My bids': 'Mes offres',
    'Job created successfully.': 'Travail cree avec succes.',
    'Failed to create job': 'Impossible de creer le travail',
    'Support Dashboard': 'Tableau de support',
    'Verify': 'Verifier',
    'Job Moderation': 'Moderation des travaux',
    'Review posted jobs from the Bookings tab and remove anything that violates ProSME rules.':
        'Verifiez les travaux publies et retirez ceux qui violent les regles ProSME.',
    'Verification decisions and email tasks are recorded in Supabase for audit review.':
        'Les decisions de verification et taches e-mail sont enregistrees pour audit.',
    'Could not load verification queue. Check Supabase policies.':
        'Impossible de charger la file de verification. Verifiez les politiques Supabase.',
    'No pending verifications': 'Aucune verification en attente',
    'New account ID submissions will appear here automatically.':
        'Les nouvelles pieces d identite apparaitront ici automatiquement.',
    'Front ID': 'Piece recto',
    'Back ID': 'Piece verso',
    'Phone': 'Telephone',
    'Categories': 'Categories',
    'Reject': 'Rejeter',
    'Approve': 'Approuver',
    'Account verified.': 'Compte verifie.',
    'Account rejected.': 'Compte rejete.',
    'Could not update verification.':
        'Impossible de mettre a jour la verification.',
    'Overview': 'Apercu',
    'Accounts': 'Comptes',
    'Tenants': 'Locataires',
    'Modules': 'Modules',
    'Could not load platform modules': 'Impossible de charger les modules',
    'Platform control': 'Controle de la plateforme',
    'Use this area to inspect account roles, tenants, marketplace modules, jobs, bids, chats, and support notifications.':
        'Utilisez cette zone pour verifier les comptes, locataires, modules, travaux, offres, discussions et alertes.',
    'Messages': 'Messages',
    'Alerts': 'Alertes',
    'No open reports': 'Aucun rapport ouvert',
    'Chat and support reports will appear here.':
        'Les rapports de discussion et support apparaitront ici.',
    'Needs review': 'A verifier',
    'Could not load reports': 'Impossible de charger les rapports',
    'No reports yet.': 'Aucun rapport pour le moment.',
    'No details provided.': 'Aucun detail fourni.',
    'reported': 'signale',
    'Dismiss': 'Ignorer',
    'Resolve': 'Resoudre',
    'Could not load accounts': 'Impossible de charger les comptes',
    'No accounts found.': 'Aucun compte trouve.',
    'tenant': 'locataire',
    'verification': 'verification',
    'active': 'actif',
    'Set': 'Definir',
    'Could not load tenants': 'Impossible de charger les locataires',
    'accounts': 'comptes',
    'users': 'utilisateurs',
    'artisans': 'artisans',
    'Could not load modules': 'Impossible de charger les modules',
    'Profiles': 'Profils',
    'Threads': 'Fils',
    'Account and role records': 'Comptes et roles',
    'Artisan service listings': 'Annonces de services artisan',
    'Customer service requests': 'Demandes de service client',
    'Negotiation offers from artisans': 'Offres de negociation des artisans',
    'Chat rooms': 'Salons de discussion',
    'Chat messages and offers': 'Messages et offres',
    'Chat, support, and safety reports':
        'Rapports discussion, support et securite',
    'Support tasks': 'Taches support',
    'Exit ProSME?': 'Quitter ProSME ?',
    'Do you want to close the app?': 'Voulez-vous fermer l application ?',
    'Stay': 'Rester',
    'Exit': 'Quitter',
    'Saved listings': 'Annonces enregistrees',
    'Saved items': 'Elements enregistres',
    'Sign in to see your bookmarked listings.':
        'Connectez-vous pour voir vos annonces favorites.',
    'Loading saved listings...': 'Chargement des annonces enregistrees...',
    'Error': 'Erreur',
    'No saved listings': 'Aucune annonce enregistree',
    'Tap the bookmark icon on any listing to save it here.':
        'Appuyez sur l icone favori d une annonce pour l enregistrer ici.',
    'Reset password': 'Reinitialiser le mot de passe',
    'Email': 'E-mail',
    'Password': 'Mot de passe',
    'Send email': 'Envoyer l e-mail',
    'Forgot password?': 'Mot de passe oublie ?',
    'Email Sign in': 'Connexion par e-mail',
    'Google Sign in': 'Connexion Google',
    'Back': 'Retour',
    'User': 'Utilisateur',
    'Creating account...': 'Creation du compte...',
    'Signing in...': 'Connexion...',
    'Password reset email sent. Check your inbox.':
        'E-mail de reinitialisation envoye. Verifiez votre boite.',
    'Account created. Click the verification link in your email, then sign in.':
        'Compte cree. Cliquez le lien de verification dans votre e-mail puis connectez-vous.',
    'Invalid email or password.': 'E-mail ou mot de passe invalide.',
    'This email is already registered. Please sign in.':
        'Cet e-mail est deja inscrit. Connectez-vous.',
    'That username is already taken. Please choose another one.':
        'Ce nom d utilisateur est deja pris. Choisissez-en un autre.',
    'Something went wrong. Please try again.':
        'Une erreur est survenue. Reessayez.',
    'Please enter email and password.': 'Entrez l e-mail et le mot de passe.',
    'Please enter a valid email.': 'Entrez un e-mail valide.',
    'Please enter a username.': 'Entrez un nom d utilisateur.',
    'Choose role': 'Choisir un role',
    'I need a service': 'J ai besoin d un service',
    'I am an artisan': 'Je suis artisan',
    'Find trusted artisans fast': 'Trouvez vite des artisans fiables',
    'Simple, icon-driven steps for customers and SMEs.':
        'Des etapes simples pour clients et PME.',
    'Get Started': 'Commencer',
    'Sign in / Sign up': 'Connexion / Inscription',
    'AI Support': 'Support IA',
    'Ask about Pro SME': 'Demandez a propos de Pro SME',
    'Support responses': 'Reponses du support',
    'No Support responses yet.': 'Aucune reponse du support.',
    'Contact support': 'Contacter le support',
    'Subject': 'Sujet',
    'What do you need help with?': 'De quoi avez-vous besoin ?',
    'Explain the issue so Support can review it.':
        'Expliquez le probleme pour que le support l examine.',
    'Sending...': 'Envoi...',
    'Send report': 'Envoyer le rapport',
    'Could not send support ticket': 'Impossible d envoyer le ticket support',
    'Invoice': 'Facture',
    'No listing selected. Open invoice from a listing.':
        'Aucune annonce selectionnee. Ouvrez la facture depuis une annonce.',
    'Subtotal': 'Sous-total',
    'Service Fee': 'Frais de service',
    'Total': 'Total',
    'Payment method': 'Methode de paiement',
    'Cash': 'Especes',
    'Confirm cash payment': 'Confirmer le paiement en especes',
    'Pay with Paystack': 'Payer avec Paystack',
    'Cash payment selected. Confirm payment with the artisan.':
        'Paiement en especes choisi. Confirmez avec l artisan.',
    'Could not open Paystack checkout.':
        'Impossible d ouvrir le paiement Paystack.',
    'Sign in to manage listings.': 'Connectez-vous pour gerer les annonces.',
    'My Listings': 'Mes annonces',
    'No listings yet. Create your first service listing.':
        'Aucune annonce. Creez votre premier service.',
    'Create listing': 'Creer une annonce',
    'Edit listing': 'Modifier l annonce',
    'Save listing': 'Enregistrer l annonce',
    'Category': 'Categorie',
    'Custom category': 'Categorie personnalisee',
    'Min price': 'Prix min.',
    'Max price': 'Prix max.',
    'Upload images': 'Importer des images',
    'images selected': 'images selectionnees',
    'Listing created.': 'Annonce creee.',
    'Listing updated.': 'Annonce mise a jour.',
    'Delete listing': 'Supprimer l annonce',
    'Listing deleted.': 'Annonce supprimee.',
    'Could not delete listing': 'Impossible de supprimer l annonce',
    'Enter a valid amount': 'Entrez un montant valide',
    'Unverified artisan': 'Artisan non verifie',
    'Continue': 'Continuer',
    'No professionals found.': 'Aucun professionnel trouve.',
    'Any': 'Tout',
    'City': 'Ville',
    'Town': 'Quartier',
    'Loading...': 'Chargement...',
    'Search': 'Rechercher',
    'Recent searches': 'Recherches recentes',
    'No service requests posted yet.': 'Aucune demande publiee.',
    'New listing': 'Nouvelle annonce',
    'Chat deleted.': 'Discussion supprimee.',
    'Could not delete chat': 'Impossible de supprimer la discussion',
    'Loading chats...': 'Chargement des discussions...',
    'Delete message': 'Supprimer le message',
    'Clear all messages': 'Effacer tous les messages',
    'Message deleted.': 'Message supprime.',
    'Messages cleared.': 'Messages effaces.',
    'Submit': 'Envoyer',
    'Report chat': 'Signaler la discussion',
    'Block chat': 'Bloquer la discussion',
    'Report sent to developer dashboard.':
        'Rapport envoye au tableau developpeur.',
    'Share conversation': 'Partager la conversation',
    'Share to phone app': 'Partager vers une application',
    'Send as SMS': 'Envoyer par SMS',
    'Forward to another chat': 'Transferer vers une autre discussion',
    'Forward to chat': 'Transferer vers une discussion',
    'No other chats available.': 'Aucune autre discussion disponible.',
    'Forwarded to chat.': 'Transfere vers la discussion.',
    'View full profile': 'Voir le profil complet',
    'User profile': 'Profil utilisateur',
    'Select all': 'Tout selectionner',
    'Delete selected': 'Supprimer la selection',
    'Report': 'Signaler',
    'Block': 'Bloquer',
    'Loading messages...': 'Chargement des messages...',
    'Start the conversation.': 'Commencez la conversation.',
    'Forwarded': 'Transfere',
    'Editing message': 'Modification du message',
    'Share location': 'Partager la localisation',
    'Share chat': 'Partager la discussion',
    'Send': 'Envoyer',
    'Save edit': 'Enregistrer',
    'Edit message': 'Modifier le message',
    'Share message': 'Partager le message',
    'Copy message': 'Copier le message',
    'Message copied.': 'Message copie.',
    'No messages to share yet.': 'Aucun message a partager.',
    'Artisan verification': 'Verification artisan',
    'Account verification': 'Verification du compte',
    'Verification approved': 'Verification approuvee',
    'Submitted and under review': 'Envoye et en cours d examen',
    'Verification paused': 'Verification en pause',
    'Upload verification documents': 'Importer les documents de verification',
    'Telephone number *': 'Numero de telephone *',
    'National ID front': 'Piece d identite recto',
    'National ID back': 'Piece d identite verso',
    'Business certificate': 'Certificat d entreprise',
    'Add business certificate': 'Ajouter un certificat',
    'Submitting...': 'Envoi...',
    'Submit for review': 'Envoyer pour examen',
    'PDF max 1 MB. Images max 5 MB.': 'PDF max 1 Mo. Images max 5 Mo.',
    'Change username': 'Changer le nom d utilisateur',
    'New username': 'Nouveau nom d utilisateur',
    'Username updated.': 'Nom d utilisateur mis a jour.',
    'Change full name': 'Changer le nom complet',
    'Full name updated.': 'Nom complet mis a jour.',
    'Security': 'Securite',
    'Change password': 'Changer le mot de passe',
    'Updates your password directly.':
        'Met a jour votre mot de passe directement.',
    'Email verification': 'Verification e-mail',
    'Your email is verified.': 'Votre e-mail est verifie.',
    'Phone number': 'Numero de telephone',
    'Verification code sent.': 'Code de verification envoye.',
    '6-digit code': 'Code a 6 chiffres',
    'Verification complete.': 'Verification terminee.',
    'New password': 'Nouveau mot de passe',
    'Confirm password': 'Confirmer le mot de passe',
    'Update password': 'Mettre a jour le mot de passe',
    'Passwords do not match.': 'Les mots de passe ne correspondent pas.',
    'Create new password': 'Creer un nouveau mot de passe',
    'Choose a new password for your account.':
        'Choisissez un nouveau mot de passe pour votre compte.',
    'Show password': 'Afficher le mot de passe',
    'Updating password...': 'Mise a jour du mot de passe...',
    'Password updated. Sign in again.':
        'Mot de passe mis a jour. Reconnectez-vous.',
    'Too many reset attempts. Please wait a few minutes and try again.':
        'Trop de tentatives. Attendez quelques minutes puis reessayez.',
    'Password reset redirect is not allowed in Supabase settings.':
        'La redirection de reinitialisation est refusee par Supabase.',
    'The reset email could not be sent. Check Supabase email settings.':
        'L e-mail n a pas pu etre envoye. Verifiez les reglages Supabase.',
    'Password updated.': 'Mot de passe mis a jour.',
    'Change phone number': 'Changer le numero de telephone',
    'Enter a valid': 'Entrez un',
    'phone number.': 'numero de telephone valide.',
    'Phone number saved.': 'Numero enregistre.',
    'Country updated.': 'Pays mis a jour.',
    'Profile description updated.': 'Description du profil mise a jour.',
    'Change email': 'Changer l e-mail',
    'Enter email address': 'Entrez l adresse e-mail',
    'Why are you deleting your account?':
        'Pourquoi supprimez-vous votre compte ?',
    'Your feedback helps us improve ProSME.':
        'Votre retour nous aide a ameliorer ProSME.',
    'Are you sure?': 'Etes-vous sur ?',
    'This will permanently remove your account. This action cannot be undone.':
        'Cela supprimera definitivement votre compte. Action irreversible.',
    'Account deleted.': 'Compte supprime.',
    'Change profile image': 'Changer l image du profil',
    'Platform wallet': 'Portefeuille de la plateforme',
    'Platform accepted work': 'Travaux acceptes de la plateforme',
    'Accepted earnings': 'Revenus acceptes',
    'Agreed spending': 'Depenses convenues',
    'Money flow across customers and artisans.':
        'Flux d argent entre clients et artisans.',
    'accepted jobs': 'travaux acceptes',
    'Wallet report': 'Rapport du portefeuille',
    'Print report': 'Imprimer le rapport',
    'Share report': 'Partager le rapport',
    'Transactions': 'Transactions',
    'Accepted bids will appear here automatically.':
        'Les offres acceptees apparaitront ici automatiquement.',
    'Accepted work': 'Travail accepte',
    'View invoice': 'Voir la facture',
    'Print invoice': 'Imprimer la facture',
    'Share invoice': 'Partager la facture',
    'Professional services marketplace': 'Marche de services professionnels',
    'Status': 'Statut',
    'Work': 'Travail',
    'Customer': 'Client',
    'Service provider': 'Prestataire',
    'Retry': 'Reessayer',
    'Could not create report': 'Impossible de creer le rapport',
    'Could not create invoice': 'Impossible de creer la facture',
    'Could not delete notification': 'Impossible de supprimer la notification',
    'Notification could not be deleted.':
        'La notification n a pas pu etre supprimee.',
    'Make sure the wallet migration has been deployed, then refresh.':
        'Verifiez que la migration du portefeuille est deployee puis actualisez.',
  },
  'Spanish': {
    'ProSME   Find Professionals': 'ProSME   Buscar profesionales',
    'ProSME': 'ProSME',
    'Home': 'Inicio',
    'Upload': 'Publicar',
    'Chat': 'Chat',
    'Chats': 'Chats',
    'Bookings': 'Reservas',
    'Profile': 'Perfil',
    'Artisan Dashboard': 'Panel de artesano',
    'Artisan': 'Artesano',
    'Listings': 'Anuncios',
    'Jobs': 'Trabajos',
    'Settings': 'Ajustes',
    'Search requests': 'Buscar solicitudes',
    'Sign in to view chats': 'Inicia sesión para ver chats',
    'No chats yet. Open a professional listing and tap Chat to start.':
        'Aún no hay chats. Abre un anuncio y toca Chat.',
    'No messages yet': 'Sin mensajes',
    'Delete chat': 'Eliminar chat',
    'Delete this conversation from your chat home?':
        '¿Eliminar esta conversación de tus chats?',
    'Cancel': 'Cancelar',
    'Delete': 'Eliminar',
    'Search results': 'Resultados de busqueda',
    'Open service requests': 'Solicitudes abiertas',
    'Matching requests': 'Solicitudes coincidentes',
    'All professionals': 'Todos los profesionales',
    'Matching professionals': 'Profesionales coincidentes',
    'Latest Artisan Updates': 'Ultimas actualizaciones',
    'No artisan updates yet.': 'Aun no hay actualizaciones.',
    'Featured Professionals': 'Profesionales destacados',
    'View All': 'Ver todo',
    'No professionals found for this search.':
        'No se encontraron profesionales para esta busqueda.',
    'Notifications': 'Notificaciones',
    'All': 'Todo',
    'Unread': 'No leidas',
    'Read': 'Leidas',
    'Type': 'Tipo',
    'Date': 'Fecha',
    'Mark read': 'Marcar como leida',
    'Notification deleted.': 'Notificacion eliminada.',
    'Wallet': 'Billetera',
    'Track accepted bids and money flow.':
        'Controla ofertas aceptadas y flujo de dinero.',
    'Work history': 'Historial de trabajos',
    'Accepted and rejected bids and requests.':
        'Ofertas aceptadas o rechazadas y solicitudes.',
    'Bid history': 'Historial de ofertas',
    'Request history': 'Historial de solicitudes',
    'Loading history...': 'Cargando historial...',
    'No bid history yet.': 'Aun no hay historial de ofertas.',
    'No request history yet.': 'Aun no hay historial de solicitudes.',
    'Could not load work history.':
        'No se pudo cargar el historial de trabajos.',
    'Wallet transactions': 'Transacciones de billetera',
    'Wallet tracking': 'Seguimiento de billetera',
    'Reports and invoices': 'Reportes y facturas',
    'Tracked amount': 'Monto registrado',
    'Completed work': 'Trabajos completados',
    'Customers': 'Clientes',
    'Artisans': 'Artesanos',
    'accepted': 'aceptado',
    'rejected': 'rechazado',
    'completed': 'completado',
    'open': 'abierto',
    'Accepted and completed bid money flow':
        'Flujo de ofertas aceptadas y completadas',
    'Tracked accepted bids': 'Ofertas aceptadas registradas',
    'Money flow from accepted work.': 'Flujo de dinero de trabajos aceptados.',
    'No wallet activity yet': 'Sin actividad en la billetera',
    'Could not load wallet.': 'No se pudo cargar la billetera.',
    'Loading wallet...': 'Cargando billetera...',
    'Hello': 'Hola',
    'Manage your services': 'Gestiona tus servicios',
    'Services': 'Servicios',
    'Bids': 'Ofertas',
    'Won': 'Ganadas',
    'Verified artisan': 'Artesano verificado',
    'Verification needed': 'Verificacion necesaria',
    'Customers can see your verified badge.':
        'Los clientes pueden ver tu insignia verificada.',
    'Upload ID documents so Support can verify your profile.':
        'Sube documentos para que soporte verifique tu perfil.',
    'My listings': 'Mis anuncios',
    'Requests': 'Solicitudes',
    'Negotiations': 'Negociaciones',
    'New Job Requests': 'Nuevas solicitudes',
    'Bid': 'Ofertar',
    'Chat after accept': 'Chat tras aceptar',
    'Enter a known address or use your phone location.':
        'Ingresa una direccion conocida o usa la ubicacion del telefono.',
    'Use current location': 'Usar ubicacion actual',
    'Location added to request.': 'Ubicacion agregada a la solicitud.',
    'Could not get location': 'No se pudo obtener la ubicacion',
    'Location permission is required.': 'Se requiere permiso de ubicacion.',
    'Job details': 'Detalles del trabajo',
    'Before you continue': 'Antes de continuar',
    'Sign in to bid or chat': 'Inicia sesion para ofertar o chatear',
    'Only artisans can bid on service requests.':
        'Solo artesanos pueden ofertar en solicitudes.',
    'budget': 'presupuesto',
    'Edit job': 'Editar trabajo',
    'Delete job': 'Eliminar trabajo',
    'Delete job request': 'Eliminar solicitud',
    'Remove job request': 'Quitar solicitud',
    'Remove': 'Quitar',
    'permanently?': 'permanentemente?',
    'from your list?': 'de tu lista?',
    'Job request deleted.': 'Solicitud eliminada.',
    'Request removed from your list.': 'Solicitud quitada de tu lista.',
    'Title': 'Titulo',
    'Description': 'Descripcion',
    'Required': 'Obligatorio',
    'Save': 'Guardar',
    'Send a bid': 'Enviar oferta',
    'Edit your bid': 'Editar tu oferta',
    'Your price': 'Tu precio',
    'Enter a valid price': 'Ingresa un precio valido',
    'Message': 'Mensaje',
    'Message is required': 'El mensaje es obligatorio',
    'Send bid and open chat': 'Enviar oferta',
    'Update bid and open chat': 'Actualizar oferta',
    'Could not send bid': 'No se pudo enviar la oferta',
    'Could not load bids': 'No se pudieron cargar ofertas',
    'won bid': 'oferta ganada',
    'Rated': 'Calificado',
    'Accept': 'Aceptar',
    'Rate artisan': 'Calificar artesano',
    'Update rating': 'Actualizar calificacion',
    'Could not open chat': 'No se pudo abrir el chat',
    'Bid accepted for': 'Oferta aceptada para',
    'Could not accept bid': 'No se pudo aceptar la oferta',
    'Comment': 'Comentario',
    'Save rating': 'Guardar calificacion',
    'Rating saved.': 'Calificacion guardada.',
    'Work location': 'Lugar del trabajo',
    'Directions': 'Direcciones',
    'Please sign in to view jobs.': 'Inicia sesion para ver trabajos.',
    'Create job': 'Crear trabajo',
    'Could not load jobs': 'No se pudieron cargar trabajos',
    'Edit bid': 'Editar oferta',
    'View bids': 'Ver ofertas',
    'View': 'Ver',
    'Create': 'Crear',
    'Search job requests': 'Buscar solicitudes de trabajo',
    'Newest first': 'Mas recientes primero',
    'Oldest first': 'Mas antiguos primero',
    'Country': 'Pais',
    'Region': 'Region',
    'Any country': 'Cualquier pais',
    'Any region': 'Cualquier region',
    'My bids': 'Mis ofertas',
    'Job created successfully.': 'Trabajo creado correctamente.',
    'Failed to create job': 'No se pudo crear el trabajo',
    'Support Dashboard': 'Panel de soporte',
    'Verify': 'Verificar',
    'Job Moderation': 'Moderacion de trabajos',
    'No pending verifications': 'Sin verificaciones pendientes',
    'Front ID': 'ID frontal',
    'Back ID': 'ID posterior',
    'Phone': 'Telefono',
    'Categories': 'Categorias',
    'Reject': 'Rechazar',
    'Approve': 'Aprobar',
    'Account verified.': 'Cuenta verificada.',
    'Account rejected.': 'Cuenta rechazada.',
    'Could not update verification.': 'No se pudo actualizar la verificacion.',
    'Overview': 'Resumen',
    'Accounts': 'Cuentas',
    'Tenants': 'Inquilinos',
    'Modules': 'Modulos',
    'Platform control': 'Control de plataforma',
    'Messages': 'Mensajes',
    'Alerts': 'Alertas',
    'No open reports': 'Sin reportes abiertos',
    'Needs review': 'Requiere revision',
    'Could not load reports': 'No se pudieron cargar reportes',
    'No reports yet.': 'Sin reportes todavia.',
    'No details provided.': 'Sin detalles.',
    'reported': 'reportado',
    'Dismiss': 'Descartar',
    'Resolve': 'Resolver',
    'Could not load accounts': 'No se pudieron cargar cuentas',
    'No accounts found.': 'No se encontraron cuentas.',
    'tenant': 'inquilino',
    'verification': 'verificacion',
    'active': 'activo',
    'Set': 'Cambiar a',
    'Could not load tenants': 'No se pudieron cargar inquilinos',
    'accounts': 'cuentas',
    'users': 'usuarios',
    'artisans': 'artesanos',
    'Could not load modules': 'No se pudieron cargar modulos',
    'Profiles': 'Perfiles',
    'Threads': 'Hilos',
    'Account and role records': 'Registros de cuentas y roles',
    'Artisan service listings': 'Anuncios de servicios artesanos',
    'Customer service requests': 'Solicitudes de clientes',
    'Negotiation offers from artisans': 'Ofertas de negociacion',
    'Chat rooms': 'Salas de chat',
    'Chat messages and offers': 'Mensajes y ofertas',
    'Support tasks': 'Tareas de soporte',
    'Exit ProSME?': '¿Salir de ProSME?',
    'Do you want to close the app?': '¿Quieres cerrar la app?',
    'Stay': 'Quedarse',
    'Exit': 'Salir',
    'Saved listings': 'Anuncios guardados',
    'Saved items': 'Elementos guardados',
    'Sign in to see your bookmarked listings.':
        'Inicia sesion para ver tus anuncios guardados.',
    'Loading saved listings...': 'Cargando anuncios guardados...',
    'Error': 'Error',
    'No saved listings': 'Sin anuncios guardados',
    'Tap the bookmark icon on any listing to save it here.':
        'Toca el marcador en cualquier anuncio para guardarlo aqui.',
    'Reset password': 'Restablecer contraseña',
    'Email': 'Correo',
    'Password': 'Contraseña',
    'Send email': 'Enviar correo',
    'Forgot password?': '¿Olvidaste tu contraseña?',
    'Email Sign in': 'Entrar con correo',
    'Google Sign in': 'Entrar con Google',
    'Back': 'Atrás',
    'User': 'Usuario',
    'Creating account...': 'Creando cuenta...',
    'Signing in...': 'Entrando...',
    'Password reset email sent. Check your inbox.':
        'Correo enviado. Revisa tu bandeja.',
    'Invalid email or password.': 'Correo o contraseña invalida.',
    'Something went wrong. Please try again.':
        'Algo salio mal. Intenta de nuevo.',
    'Choose role': 'Elegir rol',
    'I need a service': 'Necesito un servicio',
    'I am an artisan': 'Soy artesano',
    'Find trusted artisans fast': 'Encuentra artesanos confiables rapido',
    'Get Started': 'Comenzar',
    'Sign in / Sign up': 'Entrar / Registrarse',
    'AI Support': 'Soporte IA',
    'Ask about Pro SME': 'Pregunta sobre Pro SME',
    'Support responses': 'Respuestas de soporte',
    'No Support responses yet.': 'Aun no hay respuestas de soporte.',
    'Contact support': 'Contactar soporte',
    'Subject': 'Asunto',
    'What do you need help with?': '¿Con que necesitas ayuda?',
    'Sending...': 'Enviando...',
    'Send report': 'Enviar reporte',
    'Invoice': 'Factura',
    'Subtotal': 'Subtotal',
    'Service Fee': 'Cargo de servicio',
    'Total': 'Total',
    'Payment method': 'Metodo de pago',
    'Cash': 'Efectivo',
    'Confirm cash payment': 'Confirmar pago en efectivo',
    'Pay with Paystack': 'Pagar con Paystack',
    'Sign in to manage listings.': 'Inicia sesion para gestionar anuncios.',
    'My Listings': 'Mis anuncios',
    'Create listing': 'Crear anuncio',
    'Edit listing': 'Editar anuncio',
    'Save listing': 'Guardar anuncio',
    'Category': 'Categoria',
    'Custom category': 'Categoria personalizada',
    'Min price': 'Precio min.',
    'Max price': 'Precio max.',
    'Upload images': 'Subir imagenes',
    'images selected': 'imagenes seleccionadas',
    'Listing created.': 'Anuncio creado.',
    'Listing updated.': 'Anuncio actualizado.',
    'Delete listing': 'Eliminar anuncio',
    'Listing deleted.': 'Anuncio eliminado.',
    'Enter a valid amount': 'Ingresa un monto valido',
    'Unverified artisan': 'Artesano no verificado',
    'Continue': 'Continuar',
    'No professionals found.': 'No se encontraron profesionales.',
    'Any': 'Cualquiera',
    'City': 'Ciudad',
    'Town': 'Zona',
    'Loading...': 'Cargando...',
    'Search': 'Buscar',
    'Recent searches': 'Busquedas recientes',
    'No service requests posted yet.': 'No hay solicitudes publicadas.',
    'New listing': 'Nuevo anuncio',
    'Chat deleted.': 'Chat eliminado.',
    'Loading chats...': 'Cargando chats...',
    'Delete message': 'Eliminar mensaje',
    'Clear all messages': 'Borrar todos los mensajes',
    'Message deleted.': 'Mensaje eliminado.',
    'Messages cleared.': 'Mensajes borrados.',
    'Submit': 'Enviar',
    'Report chat': 'Reportar chat',
    'Block chat': 'Bloquear chat',
    'Share conversation': 'Compartir conversacion',
    'Share to phone app': 'Compartir con app',
    'Send as SMS': 'Enviar SMS',
    'Forward to another chat': 'Reenviar a otro chat',
    'Forward to chat': 'Reenviar a chat',
    'No other chats available.': 'No hay otros chats.',
    'Forwarded to chat.': 'Reenviado al chat.',
    'View full profile': 'Ver perfil completo',
    'User profile': 'Perfil de usuario',
    'Select all': 'Seleccionar todo',
    'Delete selected': 'Eliminar seleccionados',
    'Report': 'Reportar',
    'Block': 'Bloquear',
    'Loading messages...': 'Cargando mensajes...',
    'Start the conversation.': 'Inicia la conversacion.',
    'Forwarded': 'Reenviado',
    'Editing message': 'Editando mensaje',
    'Share location': 'Compartir ubicacion',
    'Share chat': 'Compartir chat',
    'Send': 'Enviar',
    'Save edit': 'Guardar cambio',
    'Edit message': 'Editar mensaje',
    'Share message': 'Compartir mensaje',
    'Copy message': 'Copiar mensaje',
    'Message copied.': 'Mensaje copiado.',
    'No messages to share yet.': 'No hay mensajes para compartir.',
    'Artisan verification': 'Verificacion de artesano',
    'Account verification': 'Verificacion de cuenta',
    'Verification approved': 'Verificacion aprobada',
    'Submitted and under review': 'Enviado y en revision',
    'Verification paused': 'Verificacion pausada',
    'Upload verification documents': 'Subir documentos de verificacion',
    'Telephone number *': 'Numero de telefono *',
    'National ID front': 'ID nacional frontal',
    'National ID back': 'ID nacional posterior',
    'Business certificate': 'Certificado comercial',
    'Add business certificate': 'Agregar certificado',
    'Submitting...': 'Enviando...',
    'Submit for review': 'Enviar para revision',
    'PDF max 1 MB. Images max 5 MB.': 'PDF max 1 MB. Imagenes max 5 MB.',
    'Change username': 'Cambiar usuario',
    'New username': 'Nuevo usuario',
    'Username updated.': 'Usuario actualizado.',
    'Change full name': 'Cambiar nombre completo',
    'Full name updated.': 'Nombre actualizado.',
    'Security': 'Seguridad',
    'Change password': 'Cambiar contraseña',
    'Email verification': 'Verificacion de correo',
    'Your email is verified.': 'Tu correo esta verificado.',
    'Phone number': 'Numero de telefono',
    'Verification code sent.': 'Codigo enviado.',
    '6-digit code': 'Codigo de 6 digitos',
    'Verification complete.': 'Verificacion completa.',
    'New password': 'Nueva contraseña',
    'Confirm password': 'Confirmar contraseña',
    'Update password': 'Actualizar contraseña',
    'Passwords do not match.': 'Las contraseñas no coinciden.',
    'Create new password': 'Crear nueva contraseña',
    'Choose a new password for your account.':
        'Elige una nueva contraseña para tu cuenta.',
    'Show password': 'Mostrar contraseña',
    'Updating password...': 'Actualizando contraseña...',
    'Password updated. Sign in again.':
        'Contraseña actualizada. Inicia sesion de nuevo.',
    'Too many reset attempts. Please wait a few minutes and try again.':
        'Demasiados intentos. Espera unos minutos e intentalo de nuevo.',
    'Password reset redirect is not allowed in Supabase settings.':
        'Supabase no permite la redireccion de restablecimiento.',
    'The reset email could not be sent. Check Supabase email settings.':
        'No se pudo enviar el correo. Revisa el correo de Supabase.',
    'Password updated.': 'Contraseña actualizada.',
    'Change phone number': 'Cambiar telefono',
    'Phone number saved.': 'Telefono guardado.',
    'Country updated.': 'Pais actualizado.',
    'Profile description updated.': 'Descripcion actualizada.',
    'Change email': 'Cambiar correo',
    'Enter email address': 'Ingresa correo',
    'Why are you deleting your account?': '¿Por que eliminas tu cuenta?',
    'Are you sure?': '¿Estas seguro?',
    'Account deleted.': 'Cuenta eliminada.',
    'Change profile image': 'Cambiar imagen de perfil',
    'Platform wallet': 'Billetera de la plataforma',
    'Platform accepted work': 'Trabajo aceptado de la plataforma',
    'Accepted earnings': 'Ingresos aceptados',
    'Agreed spending': 'Gastos acordados',
    'Money flow across customers and artisans.':
        'Flujo de dinero entre clientes y artesanos.',
    'accepted jobs': 'trabajos aceptados',
    'Wallet report': 'Reporte de billetera',
    'Print report': 'Imprimir reporte',
    'Share report': 'Compartir reporte',
    'Transactions': 'Transacciones',
    'Accepted bids will appear here automatically.':
        'Las ofertas aceptadas apareceran aqui automaticamente.',
    'Accepted work': 'Trabajo aceptado',
    'View invoice': 'Ver factura',
    'Print invoice': 'Imprimir factura',
    'Share invoice': 'Compartir factura',
    'Professional services marketplace': 'Mercado de servicios profesionales',
    'Status': 'Estado',
    'Work': 'Trabajo',
    'Customer': 'Cliente',
    'Service provider': 'Proveedor de servicio',
    'Retry': 'Reintentar',
    'Could not create report': 'No se pudo crear el reporte',
    'Could not create invoice': 'No se pudo crear la factura',
    'Could not delete notification': 'No se pudo eliminar la notificacion',
    'Notification could not be deleted.':
        'La notificacion no se pudo eliminar.',
    'Make sure the wallet migration has been deployed, then refresh.':
        'Asegurate de desplegar la migracion de billetera y actualiza.',
  },
  'Arabic': {
    'ProSME   Find Professionals': 'ProSME   ابحث عن محترفين',
    'ProSME': 'ProSME',
    'Home': 'الرئيسية',
    'Upload': 'نشر',
    'Chat': 'دردشة',
    'Chats': 'الدردشات',
    'Bookings': 'الحجوزات',
    'Profile': 'الملف الشخصي',
    'Artisan Dashboard': 'لوحة الحرفي',
    'Artisan': 'حرفي',
    'Listings': 'القوائم',
    'Jobs': 'الوظائف',
    'Settings': 'الإعدادات',
    'Search requests': 'بحث الطلبات',
    'Sign in to view chats': 'سجل الدخول لعرض الدردشات',
    'No chats yet. Open a professional listing and tap Chat to start.':
        'لا توجد دردشات بعد. افتح قائمة واضغط دردشة.',
    'No messages yet': 'لا توجد رسائل',
    'Delete chat': 'حذف الدردشة',
    'Delete this conversation from your chat home?':
        'حذف هذه المحادثة من الدردشات؟',
    'Cancel': 'إلغاء',
    'Delete': 'حذف',
    'Wallet': 'المحفظة',
    'Bid': 'عرض',
    'Requests': 'الطلبات',
    'Notifications': 'الإشعارات',
    'Job details': 'تفاصيل العمل',
    'Before you continue': 'قبل المتابعة',
    'Sign in to bid or chat': 'سجل الدخول للعرض أو الدردشة',
    'Only artisans can bid on service requests.':
        'يمكن للحرفيين فقط تقديم عروض.',
    'budget': 'الميزانية',
    'Edit job': 'تعديل العمل',
    'Delete job': 'حذف العمل',
    'Delete job request': 'حذف طلب العمل',
    'Remove job request': 'إزالة طلب العمل',
    'Remove': 'إزالة',
    'Job request deleted.': 'تم حذف الطلب.',
    'Request removed from your list.': 'تمت إزالة الطلب من قائمتك.',
    'Title': 'العنوان',
    'Description': 'الوصف',
    'Required': 'مطلوب',
    'Save': 'حفظ',
    'Send a bid': 'إرسال عرض',
    'Edit your bid': 'تعديل عرضك',
    'Your price': 'سعرك',
    'Message': 'رسالة',
    'Accept': 'قبول',
    'Rate artisan': 'تقييم الحرفي',
    'Comment': 'تعليق',
    'Work location': 'موقع العمل',
    'Directions': 'الاتجاهات',
    'Create job': 'إنشاء عمل',
    'Search job requests': 'بحث طلبات العمل',
    'Country': 'الدولة',
    'Region': 'المنطقة',
    'Location': 'الموقع',
    'My bids': 'عروضي',
    'Support Dashboard': 'لوحة الدعم',
    'Verify': 'تحقق',
    'Overview': 'نظرة عامة',
    'Accounts': 'الحسابات',
    'Tenants': 'المستأجرون',
    'Modules': 'الوحدات',
    'Messages': 'الرسائل',
    'Alerts': 'التنبيهات',
    'Approve': 'موافقة',
    'Reject': 'رفض',
    'Resolve': 'حل',
    'Dismiss': 'تجاهل',
    'No reports yet.': 'لا توجد تقارير بعد.',
    'Exit ProSME?': 'الخروج من ProSME؟',
    'Stay': 'البقاء',
    'Exit': 'خروج',
    'Saved listings': 'القوائم المحفوظة',
    'Reset password': 'إعادة تعيين كلمة المرور',
    'Email': 'البريد الإلكتروني',
    'Password': 'كلمة المرور',
    'Send email': 'إرسال بريد',
    'Back': 'رجوع',
    'User': 'مستخدم',
    'Choose role': 'اختر الدور',
    'I need a service': 'أحتاج خدمة',
    'I am an artisan': 'أنا حرفي',
    'Get Started': 'ابدأ',
    'Sign in / Sign up': 'دخول / تسجيل',
    'AI Support': 'الدعم الذكي',
    'Subject': 'الموضوع',
    'Invoice': 'فاتورة',
    'Subtotal': 'المجموع الفرعي',
    'Service Fee': 'رسوم الخدمة',
    'Total': 'الإجمالي',
    'Payment method': 'طريقة الدفع',
    'Cash': 'نقد',
    'My Listings': 'قوائمي',
    'Create listing': 'إنشاء قائمة',
    'Edit listing': 'تعديل القائمة',
    'Save listing': 'حفظ القائمة',
    'Category': 'الفئة',
    'Min price': 'أقل سعر',
    'Max price': 'أعلى سعر',
    'Upload images': 'رفع الصور',
    'Delete listing': 'حذف القائمة',
    'Listing deleted.': 'تم حذف القائمة.',
    'Any': 'أي',
    'City': 'مدينة',
    'Town': 'بلدة',
    'Loading...': 'جار التحميل...',
    'Search': 'بحث',
    'Recent searches': 'عمليات البحث الأخيرة',
    'Delete message': 'حذف الرسالة',
    'Clear all messages': 'مسح كل الرسائل',
    'Message deleted.': 'تم حذف الرسالة.',
    'Messages cleared.': 'تم مسح الرسائل.',
    'Submit': 'إرسال',
    'Share conversation': 'مشاركة المحادثة',
    'Share to phone app': 'مشاركة إلى تطبيق',
    'Send as SMS': 'إرسال كرسالة',
    'Forward to chat': 'إعادة توجيه إلى دردشة',
    'View full profile': 'عرض الملف الكامل',
    'Select all': 'تحديد الكل',
    'Delete selected': 'حذف المحدد',
    'Loading messages...': 'تحميل الرسائل...',
    'Start the conversation.': 'ابدأ المحادثة.',
    'Share location': 'مشاركة الموقع',
    'Share chat': 'مشاركة الدردشة',
    'Send': 'إرسال',
    'Edit message': 'تعديل الرسالة',
    'Share message': 'مشاركة الرسالة',
    'Copy message': 'نسخ الرسالة',
    'Artisan verification': 'توثيق الحرفي',
    'Account verification': 'توثيق الحساب',
    'Verification approved': 'تمت الموافقة',
    'Upload verification documents': 'رفع وثائق التحقق',
    'Submit for review': 'إرسال للمراجعة',
    'Change username': 'تغيير اسم المستخدم',
    'Security': 'الأمان',
    'Change password': 'تغيير كلمة المرور',
    'Phone number': 'رقم الهاتف',
    'Delete account': 'حذف الحساب',
    'Are you sure?': 'هل أنت متأكد؟',
    'Account deleted.': 'تم حذف الحساب.',
    'Hello': 'مرحباً',
    'Favourites': 'المفضلة',
    'saved listing': 'قائمة محفوظة',
    'saved listings': 'قوائم محفوظة',
    'Tap to view your saved listings.': 'اضغط لعرض القوائم المحفوظة.',
    'Verification': 'التحقق',
    'pending': 'قيد المراجعة',
    'Submit or update your ID for Support review.':
        'أرسل أو حدّث هويتك لمراجعة الدعم.',
    'Account settings': 'إعدادات الحساب',
    'Username, phone, email, password, and privacy.':
        'اسم المستخدم والهاتف والبريد وكلمة المرور والخصوصية.',
    'Open': 'فتح',
    'App settings': 'إعدادات التطبيق',
    'Language, dark mode, and notifications.':
        'اللغة والوضع الداكن والإشعارات.',
    'History, bid, chat, and account alerts.':
        'السجل والعروض والدردشة وتنبيهات الحساب.',
    'Track accepted bids and money flow.':
        'تتبع العروض المقبولة وتدفق الأموال.',
    'Logout': 'تسجيل الخروج',
    'Dark mode': 'الوضع الداكن',
    'Email notifications': 'إشعارات البريد',
    'Phone notifications': 'إشعارات الهاتف',
    'Language': 'اللغة',
    'Currency': 'العملة',
    'Username': 'اسم المستخدم',
    'Full name': 'الاسم الكامل',
    'Profile description': 'وصف الملف',
    'What do you do?': 'ما هو عملك؟',
    'Enter email address': 'أدخل البريد الإلكتروني',
    'New username': 'اسم مستخدم جديد',
    'New password': 'كلمة مرور جديدة',
    'Confirm password': 'تأكيد كلمة المرور',
    '6-digit code': 'رمز من 6 أرقام',
    'Telephone number *': 'رقم الهاتف *',
    'Service title': 'عنوان الخدمة',
    'Describe your need': 'صف احتياجك',
    'Budget': 'الميزانية',
    'Type location, street, or area': 'اكتب الموقع أو الشارع أو المنطقة',
    'What service or job do you need?': 'ما الخدمة أو العمل الذي تحتاجه؟',
    'Platform wallet': 'محفظة المنصة',
    'Platform accepted work': 'الأعمال المقبولة في المنصة',
    'Accepted earnings': 'الأرباح المقبولة',
    'Agreed spending': 'الإنفاق المتفق عليه',
    'Money flow across customers and artisans.':
        'تدفق الأموال بين العملاء والحرفيين.',
    'accepted jobs': 'أعمال مقبولة',
    'Wallet report': 'تقرير المحفظة',
    'Print report': 'طباعة التقرير',
    'Share report': 'مشاركة التقرير',
    'Transactions': 'المعاملات',
    'Accepted bids will appear here automatically.':
        'ستظهر العروض المقبولة هنا تلقائياً.',
    'Accepted work': 'عمل مقبول',
    'View invoice': 'عرض الفاتورة',
    'Print invoice': 'طباعة الفاتورة',
    'Share invoice': 'مشاركة الفاتورة',
    'Professional services marketplace': 'سوق الخدمات المهنية',
    'Status': 'الحالة',
    'Work': 'العمل',
    'Customer': 'العميل',
    'Service provider': 'مقدم الخدمة',
    'Refresh': 'تحديث',
    'Retry': 'إعادة المحاولة',
    'Could not delete notification': 'تعذر حذف الإشعار',
    'Notification could not be deleted.': 'لم يتم حذف الإشعار.',
    'All': 'الكل',
    'Unread': 'غير مقروء',
    'Read': 'مقروء',
    'Type': 'النوع',
    'Date': 'التاريخ',
    'Mark read': 'تعليم كمقروء',
    'Notification deleted.': 'تم حذف الإشعار.',
    'New job request': 'طلب عمل جديد',
    'Support update': 'تحديث الدعم',
    'New support ticket': 'تذكرة دعم جديدة',
    'job created': 'تم إنشاء العمل',
    'developer response': 'رد المطور',
    'support ticket': 'تذكرة دعم',
    'Your support ticket has been reviewed.': 'تمت مراجعة تذكرة الدعم.',
    'Verified account': 'حساب موثق',
    'Verified artisan': 'حرفي موثق',
    'Create account': 'إنشاء حساب',
    'Sign in': 'تسجيل الدخول',
    'Email Sign in': 'الدخول بالبريد',
    'Forgot password?': 'نسيت كلمة المرور؟',
    'Close': 'إغلاق',
    'Edit': 'تعديل',
    'Continue': 'متابعة',
    'Clear': 'مسح',
    'About': 'حول',
    'About Pro SME': 'حول Pro SME',
    'Account security': 'أمان الحساب',
    'active': 'نشط',
    'Active services': 'الخدمات النشطة',
    'Add a phone number in account settings.':
        'أضف رقم هاتف في إعدادات الحساب.',
    'Add business certificate': 'إضافة شهادة تجارية',
    'Add full name': 'إضافة الاسم الكامل',
    'Add phone': 'إضافة هاتف',
    'Add profile description': 'إضافة وصف الملف',
    'All professionals': 'كل المحترفين',
    'Artisan profile': 'ملف الحرفي',
    'artisans': 'حرفيون',
    'Ask about Pro SME': 'اسأل عن Pro SME',
    'Back ID': 'خلف الهوية',
    'Bid accepted for': 'تم قبول العرض لـ',
    'Bids': 'العروض',
    'Bids won': 'العروض الفائزة',
    'Block': 'حظر',
    'Business certificate': 'شهادة تجارية',
    'Categories': 'الفئات',
    'Change full name': 'تغيير الاسم الكامل',
    'Change phone number': 'تغيير رقم الهاتف',
    'Change profile image': 'تغيير صورة الملف',
    'Chat blocked and reported.': 'تم حظر الدردشة والإبلاغ عنها.',
    'Chat deleted.': 'تم حذف الدردشة.',
    'Clear date filter': 'مسح فلتر التاريخ',
    'Comments': 'التعليقات',
    'Completed reviews': 'المراجعات المكتملة',
    'Contact support': 'الاتصال بالدعم',
    'Could not accept bid': 'تعذر قبول العرض',
    'Could not access phone location': 'تعذر الوصول لموقع الهاتف',
    'Could not block chat': 'تعذر حظر الدردشة',
    'Could not clear messages': 'تعذر مسح الرسائل',
    'Could not create invoice': 'تعذر إنشاء الفاتورة',
    'Could not create listing': 'تعذر إنشاء القائمة',
    'Could not create report': 'تعذر إنشاء التقرير',
    'Could not delete account': 'تعذر حذف الحساب',
    'Could not delete chat': 'تعذر حذف الدردشة',
    'Could not delete job request': 'تعذر حذف طلب العمل',
    'Could not delete listing': 'تعذر حذف القائمة',
    'Could not delete message': 'تعذر حذف الرسالة',
    'Could not delete messages': 'تعذر حذف الرسائل',
    'Could not find the other user.': 'تعذر العثور على المستخدم الآخر.',
    'Could not forward message': 'تعذر إعادة توجيه الرسالة',
    'Could not get location': 'تعذر الحصول على الموقع',
    'Could not load accounts': 'تعذر تحميل الحسابات',
    'Could not load bids': 'تعذر تحميل العروض',
    'Could not load jobs': 'تعذر تحميل الأعمال',
    'Could not load messages.': 'تعذر تحميل الرسائل.',
    'Could not load modules': 'تعذر تحميل الوحدات',
    'Could not load notifications.': 'تعذر تحميل الإشعارات.',
    'Could not load professional profile.': 'تعذر تحميل ملف المحترف.',
    'Could not load reports': 'تعذر تحميل التقارير',
    'Could not load requests': 'تعذر تحميل الطلبات',
    'Could not load tenants': 'تعذر تحميل المستأجرين',
    'Could not load this job': 'تعذر تحميل هذا العمل',
    'Could not load wallet.': 'تعذر تحميل المحفظة.',
    'Could not open chat': 'تعذر فتح الدردشة',
    'Could not open Paystack checkout.': 'تعذر فتح دفع Paystack.',
    'Could not open SMS app.': 'تعذر فتح تطبيق الرسائل.',
    'Could not save listing': 'تعذر حفظ القائمة',
    'Could not save rating': 'تعذر حفظ التقييم',
    'Could not send bid': 'تعذر إرسال العرض',
    'Could not send code': 'تعذر إرسال الرمز',
    'Could not send report': 'تعذر إرسال التقرير',
    'Work history': 'سجل الأعمال',
    'Accepted and rejected bids and requests.':
        'العروض المقبولة والمرفوضة والطلبات.',
    'Bid history': 'سجل العروض',
    'Request history': 'سجل الطلبات',
    'Loading history...': 'جار تحميل السجل...',
    'No bid history yet.': 'لا يوجد سجل عروض بعد.',
    'No request history yet.': 'لا يوجد سجل طلبات بعد.',
    'Could not load work history.': 'تعذر تحميل سجل الأعمال.',
    'Wallet transactions': 'معاملات المحفظة',
    'Wallet tracking': 'تتبع المحفظة',
    'Reports and invoices': 'التقارير والفواتير',
    'Tracked amount': 'المبلغ المتتبع',
    'Completed work': 'الأعمال المكتملة',
    'Customers': 'العملاء',
    'Artisans': 'الحرفيون',
    'accepted': 'مقبول',
    'rejected': 'مرفوض',
    'completed': 'مكتمل',
    'open': 'مفتوح',
    'Accepted and completed bid money flow':
        'تدفق أموال العروض المقبولة والمكتملة',
    'Create new password': 'إنشاء كلمة مرور جديدة',
    'Choose a new password for your account.': 'اختر كلمة مرور جديدة لحسابك.',
    'Show password': 'إظهار كلمة المرور',
    'Updating password...': 'جار تحديث كلمة المرور...',
    'Password updated. Sign in again.':
        'تم تحديث كلمة المرور. سجل الدخول مرة أخرى.',
    'Too many reset attempts. Please wait a few minutes and try again.':
        'محاولات كثيرة. انتظر بضع دقائق ثم حاول مرة أخرى.',
    'Password reset redirect is not allowed in Supabase settings.':
        'إعادة توجيه كلمة المرور غير مسموحة في إعدادات Supabase.',
    'The reset email could not be sent. Check Supabase email settings.':
        'تعذر إرسال البريد. تحقق من إعدادات البريد في Supabase.',
  },
  'Twi': {
    'ProSME   Find Professionals': 'ProSME   Hwehwɛ adwumayɛfo',
    'Home': 'Fie',
    'Upload': 'Fa so',
    'Chat': 'Nkɔmmɔ',
    'Chats': 'Nkɔmmɔ',
    'Bookings': 'Nhyehyɛe',
    'Profile': 'Wo ho nsɛm',
    'Artisan Dashboard': 'Adwumfoɔ Dashboard',
    'Listings': 'Nnwuma',
    'Jobs': 'Adwuma',
    'Settings': 'Nhyehyɛe',
    'Wallet': 'Sika kotoku',
    'Bid': 'Fa bo',
    'Requests': 'Abisade',
    'Notifications': 'Amanesebɔ',
    'Delete': 'Yi fi hɔ',
    'Job details': 'Adwuma ho nsɛm',
    'Before you continue': 'Ansa na woatoa so',
    'Sign in to bid or chat': 'Kɔ mu na fa bo anaa kasa',
    'Only artisans can bid on service requests.':
        'Adwumfoɔ nko ara na wobetumi afa bo.',
    'budget': 'sika nhyehyɛe',
    'Edit job': 'Sesa adwuma',
    'Delete job': 'Yi adwuma fi hɔ',
    'Delete job request': 'Yi adwuma abisade fi hɔ',
    'Remove job request': 'Yi abisade no fi wo list mu',
    'Remove': 'Yi fi hɔ',
    'Job request deleted.': 'Wayi abisade no afi hɔ.',
    'Request removed from your list.': 'Wayi abisade no afi wo list mu.',
    'Title': 'Ti asɛm',
    'Description': 'Nkyerɛkyerɛmu',
    'Required': 'Ɛho hia',
    'Save': 'Sie',
    'Send a bid': 'Fa bo kɔ',
    'Edit your bid': 'Sesa wo bo',
    'Your price': 'Wo bo',
    'Message': 'Nkra',
    'Accept': 'Gye tom',
    'Rate artisan': 'Ma adwumfoɔ abasobɔde',
    'Comment': 'Adwenkyerɛ',
    'Work location': 'Adwuma beae',
    'Directions': 'Kwan kyerɛ',
    'Create job': 'Bɔ adwuma foforo',
    'Search job requests': 'Hwehwɛ adwuma abisade',
    'Country': 'Ɔman',
    'Region': 'Mantam',
    'Location': 'Beae',
    'My bids': 'Me boɔ',
    'Support Dashboard': 'Mmoa dashboard',
    'Verify': 'Hwɛ mu',
    'Overview': 'Nsɛm nyinaa',
    'Accounts': 'Akawnt',
    'Tenants': 'Tenants',
    'Modules': 'Modules',
    'Messages': 'Nkra',
    'Alerts': 'Kɔkɔbɔ',
    'Approve': 'Pene so',
    'Reject': 'Pow',
    'Resolve': 'Siesie',
    'Dismiss': 'Gyae',
    'No reports yet.': 'Report biara nni hɔ.',
    'Exit ProSME?': 'Pue fi ProSME?',
    'Stay': 'Tena',
    'Exit': 'Pue',
    'Saved listings': 'Nnwuma a woasie',
    'Reset password': 'Sesa password',
    'Email': 'Email',
    'Password': 'Password',
    'Send email': 'Soma email',
    'Back': 'San akyi',
    'User': 'Dwumadini',
    'Choose role': 'Paw wo dwuma',
    'I need a service': 'Mehia service',
    'I am an artisan': 'Meyɛ adwumfoɔ',
    'Get Started': 'Hyɛ ase',
    'Sign in / Sign up': 'Kɔ mu / Kyerɛw wo din',
    'AI Support': 'AI mmoa',
    'Subject': 'Asɛmti',
    'Invoice': 'Invoice',
    'Subtotal': 'Subtotal',
    'Service Fee': 'Service sika',
    'Total': 'Ne nyinaa',
    'Payment method': 'Sika tua kwan',
    'Cash': 'Sika',
    'My Listings': 'Me listings',
    'Create listing': 'Yɛ listing',
    'Edit listing': 'Sesa listing',
    'Save listing': 'Sie listing',
    'Category': 'Nkyekyɛmu',
    'Min price': 'Bo ketewa',
    'Max price': 'Bo kɛse',
    'Upload images': 'Fa mfoni so',
    'Delete listing': 'Yi listing fi hɔ',
    'Listing deleted.': 'Wayi listing afi hɔ.',
    'Any': 'Biara',
    'City': 'Kurow',
    'Town': 'Town',
    'Loading...': 'Ɛreba...',
    'Search': 'Hwehwɛ',
    'Recent searches': 'Nhwehwɛmu foforo',
    'Delete message': 'Yi nkra fi hɔ',
    'Clear all messages': 'Pepa nkra nyinaa',
    'Message deleted.': 'Wayi nkra afi hɔ.',
    'Messages cleared.': 'Wɔapepa nkra.',
    'Submit': 'Soma',
    'Share conversation': 'Kyɛ nkɔmmɔ',
    'Share to phone app': 'Kyɛ kɔ phone app',
    'Send as SMS': 'Soma SMS',
    'Forward to chat': 'Fa kɔ chat foforo',
    'View full profile': 'Hwɛ profile nyinaa',
    'Select all': 'Paw nyinaa',
    'Delete selected': 'Yi nea wapaw',
    'Loading messages...': 'Nkratoɔ reba...',
    'Start the conversation.': 'Hyɛ nkɔmmɔ ase.',
    'Share location': 'Kyɛ beae',
    'Share chat': 'Kyɛ chat',
    'Send': 'Soma',
    'Edit message': 'Sesa nkra',
    'Share message': 'Kyɛ nkra',
    'Copy message': 'Copy nkra',
    'Artisan verification': 'Adwumfoɔ verification',
    'Account verification': 'Account verification',
    'Verification approved': 'Wɔapene so',
    'Upload verification documents': 'Fa verification papers so',
    'Submit for review': 'Soma ma wɔnhwɛ',
    'Change username': 'Sesa username',
    'Security': 'Banbɔ',
    'Change password': 'Sesa password',
    'Phone number': 'Phone number',
    'Delete account': 'Yi account fi hɔ',
    'Are you sure?': 'Wo gye di?',
    'Account deleted.': 'Wayi account afi hɔ.',
    'Hello': 'Akwaaba',
    'Favourites': 'Nea wopɛ',
    'saved listing': 'listing a woasie',
    'saved listings': 'listings a woasie',
    'Tap to view your saved listings.': 'Mia so hwɛ listings a woasie.',
    'Verification': 'Nhwehwɛmu',
    'pending': 'Wɔrehwɛ mu',
    'Submit or update your ID for Support review.':
        'Fa wo ID soma anaa sesa ma Support nhwɛ mu.',
    'Account settings': 'Account nhyehyɛe',
    'Username, phone, email, password, and privacy.':
        'Username, phone, email, password ne kokoamsɛm.',
    'Open': 'Bue',
    'App settings': 'App nhyehyɛe',
    'Language, dark mode, and notifications.': 'Kasa, sum mode ne amanneɛbɔ.',
    'History, bid, chat, and account alerts.':
        'Abakɔsɛm, boɔ, nkɔmmɔ ne account kɔkɔbɔ.',
    'Track accepted bids and money flow.':
        'Hwɛ boɔ a wɔagye atom ne sika nkɔso.',
    'Logout': 'Pue account mu',
    'Dark mode': 'Sum mode',
    'Email notifications': 'Email amanneɛbɔ',
    'Phone notifications': 'Phone amanneɛbɔ',
    'Language': 'Kasa',
    'Currency': 'Sika su',
    'Username': 'Username',
    'Full name': 'Din nyinaa',
    'Profile description': 'Wo ho nkyerɛkyerɛmu',
    'What do you do?': 'Adwuma bɛn na woyɛ?',
    'Enter email address': 'Kyerɛw email address',
    'New username': 'Username foforo',
    'New password': 'Password foforo',
    'Confirm password': 'Si password no pi',
    '6-digit code': 'Nɔma 6 code',
    'Telephone number *': 'Phone number *',
    'Service title': 'Service din',
    'Describe your need': 'Kyerɛ nea wohia',
    'Budget': 'Sika nhyehyɛe',
    'Type location, street, or area': 'Kyerɛw beae, kwan anaa mantam',
    'What service or job do you need?': 'Service anaa adwuma bɛn na wohia?',
    'Platform wallet': 'Platform sika kotoku',
    'Platform accepted work': 'Platform adwuma a wɔagye atom',
    'Accepted earnings': 'Sika a wɔagye atom',
    'Agreed spending': 'Sika a moapene so',
    'Money flow across customers and artisans.':
        'Sika nkɔso wɔ customers ne adwumfoɔ ntam.',
    'accepted jobs': 'nnwuma a wɔagye atom',
    'Wallet report': 'Sika kotoku report',
    'Print report': 'Print report',
    'Share report': 'Kyɛ report',
    'Transactions': 'Sika dwumadie',
    'Accepted bids will appear here automatically.':
        'Boɔ a wɔagye atom bɛba ha ankasa.',
    'Accepted work': 'Adwuma a wɔagye atom',
    'View invoice': 'Hwɛ invoice',
    'Print invoice': 'Print invoice',
    'Share invoice': 'Kyɛ invoice',
    'Professional services marketplace': 'Adwumayɛfoɔ gua',
    'Status': 'Tebea',
    'Work': 'Adwuma',
    'Customer': 'Customer',
    'Service provider': 'Adwumfoɔ',
    'Refresh': 'Yɛ foforo',
    'Retry': 'San yɛ',
    'Could not delete notification': 'Antumi anyi amanneɛbɔ no',
    'Notification could not be deleted.': 'Wɔantumi anyi amanneɛbɔ no.',
    'All': 'Nyinaa',
    'Unread': 'Wɔnnkenkan',
    'Read': 'Wɔakenkan',
    'Type': 'Su',
    'Date': 'Da',
    'Mark read': 'Hyɛ sɛ wɔakenkan',
    'Notification deleted.': 'Wayi amanneɛbɔ no afi hɔ.',
    'New job request': 'Adwuma abisade foforo',
    'Support update': 'Support nsakrae',
    'New support ticket': 'Support ticket foforo',
    'job created': 'Wɔabɔ adwuma',
    'developer response': 'Developer mmuae',
    'support ticket': 'Support ticket',
    'Your support ticket has been reviewed.': 'Wɔahwɛ wo support ticket no mu.',
    'Verified account': 'Account a wɔagye atom',
    'Verified artisan': 'Adwumfoɔ a wɔagye atom',
    'Create account': 'Yɛ account',
    'Sign in': 'Kɔ mu',
    'Email Sign in': 'Fa email kɔ mu',
    'Forgot password?': 'Wo werɛ afi password?',
    'Close': 'To mu',
    'Edit': 'Sesa',
    'Continue': 'Toa so',
    'Clear': 'Pepa',
    'About': 'Ɛfa ho',
    'About Pro SME': 'Ɛfa Pro SME ho',
    'Account security': 'Account banbɔ',
    'active': 'Ɛyɛ adwuma',
    'Active services': 'Services a ɛyɛ adwuma',
    'Add a phone number in account settings.':
        'Fa phone number ka account nhyehyɛe ho.',
    'Add business certificate': 'Fa business certificate ka ho',
    'Add full name': 'Fa din nyinaa ka ho',
    'Add phone': 'Fa phone ka ho',
    'Add profile description': 'Fa profile nkyerɛkyerɛmu ka ho',
    'All professionals': 'Adwumayɛfoɔ nyinaa',
    'Artisan': 'Adwumfoɔ',
    'Artisan profile': 'Adwumfoɔ profile',
    'artisans': 'adwumfoɔ',
    'Ask about Pro SME': 'Bisa Pro SME ho asɛm',
    'Back ID': 'ID akyi',
    'Bid accepted for': 'Wɔagye boɔ atom ama',
    'Bids': 'Boɔ ahorow',
    'Bids won': 'Boɔ a adi nkonim',
    'Block': 'Si kwan',
    'Business certificate': 'Business certificate',
    'Cancel': 'Twa mu',
    'Categories': 'Nkyekyɛmu',
    'Change full name': 'Sesa din nyinaa',
    'Change phone number': 'Sesa phone number',
    'Change profile image': 'Sesa profile mfoni',
    'Chat blocked and reported.': 'Wɔasi chat no kwan na wɔabɔ amanneɛ.',
    'Chat deleted.': 'Wayi chat afi hɔ.',
    'Clear date filter': 'Pepa da filter',
    'Comments': 'Adwenkyerɛ',
    'Completed reviews': 'Reviews a wɔawie',
    'Contact support': 'Frɛ Support',
    'Could not accept bid': 'Antumi annye boɔ no atom',
    'Could not access phone location': 'Antumi annya phone beae',
    'Could not block chat': 'Antumi ansi chat no kwan',
    'Could not clear messages': 'Antumi ampepa nkra',
    'Could not create invoice': 'Antumi anyɛ invoice',
    'Could not create listing': 'Antumi anyɛ listing',
    'Could not create report': 'Antumi anyɛ report',
    'Could not delete account': 'Antumi anyi account afi hɔ',
    'Could not delete chat': 'Antumi anyi chat afi hɔ',
    'Could not delete job request': 'Antumi anyi adwuma abisade afi hɔ',
    'Could not delete listing': 'Antumi anyi listing afi hɔ',
    'Could not delete message': 'Antumi anyi nkra afi hɔ',
    'Could not delete messages': 'Antumi anyi nkratoɔ afi hɔ',
    'Could not find the other user.': 'Antumi anhu onipa foforo no.',
    'Could not forward message': 'Antumi ansoma nkra no ankɔ anim',
    'Could not get location': 'Antumi annya beae',
    'Could not load accounts': 'Antumi anfa accounts no amma',
    'Could not load bids': 'Antumi anfa boɔ no amma',
    'Could not load jobs': 'Antumi anfa nnwuma no amma',
    'Could not load messages.': 'Antumi anfa nkratoɔ no amma.',
    'Could not load modules': 'Antumi anfa modules no amma',
    'Could not load notifications.': 'Antumi anfa amanneɛbɔ no amma.',
    'Could not load professional profile.':
        'Antumi anfa adwumayɛfoɔ profile no amma.',
    'Could not load reports': 'Antumi anfa reports no amma',
    'Could not load requests': 'Antumi anfa abisade no amma',
    'Could not load tenants': 'Antumi anfa tenants no amma',
    'Could not load this job': 'Antumi anfa adwuma yi amma',
    'Could not load wallet.': 'Antumi anfa sika kotoku no amma.',
    'Could not open chat': 'Antumi ammue chat',
    'Could not open Paystack checkout.': 'Antumi ammue Paystack payment.',
    'Could not open SMS app.': 'Antumi ammue SMS app.',
    'Could not save listing': 'Antumi ansie listing',
    'Could not save rating': 'Antumi ansie rating',
    'Could not send bid': 'Antumi ansoma boɔ',
    'Could not send code': 'Antumi ansoma code',
    'Could not send report': 'Antumi ansoma report',
    'Work history': 'Adwuma abakosem',
    'Accepted and rejected bids and requests.':
        'Bo a woagye atom anaa woapo ne abisade.',
    'Bid history': 'Bo abakosem',
    'Request history': 'Abisade abakosem',
    'Loading history...': 'Yerefa abakosem no...',
    'No bid history yet.': 'Bo abakosem biara nni ho.',
    'No request history yet.': 'Abisade abakosem biara nni ho.',
    'Could not load work history.': 'Yentumi anfa adwuma abakosem no amma.',
    'Wallet transactions': 'Sika kotoku nkitahodi',
    'Wallet tracking': 'Sika kotoku nhwehwemu',
    'Reports and invoices': 'Report ne invoice',
    'Tracked amount': 'Sika a woahwehwe mu',
    'Completed work': 'Adwuma a woawie',
    'Customers': 'Adetofo',
    'Artisans': 'Adwumfo',
    'accepted': 'woagye atom',
    'rejected': 'woapo',
    'completed': 'awie',
    'open': 'abue',
    'Accepted and completed bid money flow':
        'Bo a woagye atom ne nea woawie no sika nkoso',
    'Create new password': 'Yɛ password foforo',
    'Choose a new password for your account.':
        'Paw password foforo ma wo account.',
    'Show password': 'Kyerɛ password',
    'Updating password...': 'Yeresesa password...',
    'Password updated. Sign in again.': 'Woasesa password. Kɔ mu bio.',
    'Too many reset attempts. Please wait a few minutes and try again.':
        'Woasɔ ahwɛ mpɛn pii. Twɛn kakra na san sɔ hwɛ.',
    'Password reset redirect is not allowed in Supabase settings.':
        'Supabase mma password reset kwan no ho kwan.',
    'The reset email could not be sent. Check Supabase email settings.':
        'Yentumi ansoma reset email no. Hwɛ Supabase email nhyehyɛe.',
  },
};

class AppSettingsController extends StateNotifier<AppSettings> {
  AppSettingsController(super.state);

  static AppSettings _initialSettings = const AppSettings();

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLanguage = prefs.getString(_languageKey) ?? 'English';
    final language = kSupportedAppLanguages.contains(savedLanguage)
        ? savedLanguage
        : 'English';
    if (language != savedLanguage) {
      await prefs.setString(_languageKey, language);
    }
    _initialSettings = AppSettings(
      language: language,
      currencyCode: prefs.getString(_currencyCodeKey) ?? 'GHS',
      emailNotifications: prefs.getBool(_emailNotificationsKey) ?? true,
      phoneNotifications: prefs.getBool(_phoneNotificationsKey) ?? true,
    );
    final cachedRate = prefs
        .getDouble('$_currencyRateKeyPrefix${_initialSettings.currencyCode}');
    if (cachedRate != null) {
      setCurrencyRateFromGhs(_initialSettings.currencyCode, cachedRate);
    }
    unawaited(_refreshCurrencyRate(_initialSettings.currencyCode, prefs));
  }

  Future<void> setCurrencyCode(String currencyCode) async {
    state = state.copyWith(currencyCode: currencyCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_currencyCodeKey, currencyCode);
    final cachedRate = prefs.getDouble('$_currencyRateKeyPrefix$currencyCode');
    if (cachedRate != null) setCurrencyRateFromGhs(currencyCode, cachedRate);
    await _refreshCurrencyRate(currencyCode, prefs);
  }

  static Future<void> _refreshCurrencyRate(
    String currencyCode,
    SharedPreferences prefs,
  ) async {
    if (currencyCode == 'GHS') {
      setCurrencyRateFromGhs('GHS', 1);
      await prefs.setDouble('${_currencyRateKeyPrefix}GHS', 1);
      return;
    }
    try {
      final uri = Uri.parse('https://open.er-api.com/v6/latest/GHS');
      final response = await http.get(uri).timeout(const Duration(seconds: 5));
      if (response.statusCode < 200 || response.statusCode >= 300) return;
      final decoded = jsonDecode(response.body);
      if (decoded is! Map<String, dynamic>) return;
      final rates = decoded['rates'];
      if (rates is! Map) return;
      final rawRate = rates[currencyCode];
      final rate = rawRate is num ? rawRate.toDouble() : null;
      if (rate == null || rate <= 0) return;
      setCurrencyRateFromGhs(currencyCode, rate);
      await prefs.setDouble('$_currencyRateKeyPrefix$currencyCode', rate);
    } catch (_) {
      // Built-in fallback rates keep the app usable offline.
    }
  }

  Future<void> setLanguage(String language) async {
    final normalized =
        kSupportedAppLanguages.contains(language) ? language : 'English';
    state = state.copyWith(language: normalized);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, normalized);
  }

  Future<void> setEmailNotifications(bool enabled) async {
    state = state.copyWith(emailNotifications: enabled);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_emailNotificationsKey, enabled);
  }

  Future<void> setPhoneNotifications(bool enabled) async {
    state = state.copyWith(phoneNotifications: enabled);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_phoneNotificationsKey, enabled);
  }
}
